# config.py

CAPITAL = 4700
LEVERAGE = 5
EFFECTIVE_CAPITAL = CAPITAL * LEVERAGE

MAX_TRADES_PER_DAY = 1
MAX_DAILY_LOSS_RS = 70   # hard stop
BROKERAGE_PER_TRADE = 40
OTHER_CHARGES = 10

TOTAL_CHARGES = BROKERAGE_PER_TRADE + OTHER_CHARGES
